import type { JamendoDocSource } from '../schemas/index.ts';

export const JAMENDO_DOC_SOURCE: JamendoDocSource = {
    baseUrl: 'https://developer.jamendo.com/v3.0',
    pages: [
        { path: 'docs', dest: '00-introduction.md' },
        { path: 'authentication', dest: '01-authentication.md' },
        { path: 'response-codes', dest: '02-response-codes.md' },
        { path: 'albums', dest: 'read/albums.md' },
        { path: 'albums/file', dest: 'read/albums-file.md' },
        { path: 'albums/tracks', dest: 'read/albums-tracks.md' },
        { path: 'albums/musicinfo', dest: 'read/albums-musicinfo.md' },
        { path: 'artists', dest: 'read/artists.md' },
        { path: 'artists/tracks', dest: 'read/artists-tracks.md' },
        { path: 'artists/albums', dest: 'read/artists-albums.md' },
        { path: 'artists/locations', dest: 'read/artists-locations.md' },
        { path: 'artists/musicinfo', dest: 'read/artists-musicinfo.md' },
        { path: 'autocomplete', dest: 'read/autocomplete.md' },
        { path: 'feeds', dest: 'read/feeds.md' },
        { path: 'playlists', dest: 'read/playlists.md' },
        { path: 'playlists/file', dest: 'read/playlists-file.md' },
        { path: 'playlists/tracks', dest: 'read/playlists-tracks.md' },
        { path: 'radios', dest: 'read/radios.md' },
        { path: 'radios/stream', dest: 'read/radios-stream.md' },
        { path: 'reviews/albums', dest: 'read/reviews-albums.md' },
        { path: 'reviews/tracks', dest: 'read/reviews-tracks.md' },
        { path: 'tracks', dest: 'read/tracks.md' },
        { path: 'tracks/file', dest: 'read/tracks-file.md' },
        { path: 'tracks/similar', dest: 'read/tracks-similar.md' },
        { path: 'users', dest: 'read/users.md' },
        { path: 'users/artists', dest: 'read/users-artists.md' },
        { path: 'users/albums', dest: 'read/users-albums.md' },
        { path: 'users/tracks', dest: 'read/users-tracks.md' },
        { path: 'setuser/fan', dest: 'write/setuser-fan.md' },
        { path: 'setuser/favorite', dest: 'write/setuser-favorite.md' },
        { path: 'setuser/like', dest: 'write/setuser-like.md' },
        { path: 'setuser/dislike', dest: 'write/setuser-dislike.md' },
        { path: 'setuser/myalbum', dest: 'write/setuser-myalbum.md' },
    ],
};
